name: Validate Collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install bioimageio.spec
      run: pip install bioimageio.spec lxml
    - name: validate collection
      run: bioimageio validate-partner-collection collection.yaml
